services:
   type: web
    name: fastapi-app
    env: python
    region: frankfurt   
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
